### ISSUE TITLE
How was this project implemented?

### ISSUE THREAD

**Issue by Helshr** [coleh2/python-parser#2]
Thank you very much. How was this project implemented?

**Comment by Helshr** [comment]
PythonParser.pegjs and test-output.json Where did you get the contents of these two files?

**Comment by chlohal** [comment]
Hi, thanks for your question! I used [pegjs/pegjs](https://github.com/pegjs/pegjs) as the framework when I was writing this project. 

I wrote `python-parser.pegjs` manually (based off of [this official doc](https://github.com/python/cpython/blob/3.9/Grammar/Grammar))

I then put it into [the online PegJS tool](https://pegjs.org/online), and used the file `test.py` to generate `test-output.json`

**Comment by chlohal** [comment]
Does that help, sorry? please tell me if not & I can clarify further!

**Comment by Helshr** [comment]
Thank you, I learned a lot!
